### ISSUE TITLE
Readme?

### ISSUE THREAD

**Issue by oblivioncth** [firstof9/ha-nws#5]
While I get that you most likely drafted this for your own usage and kind of just threw it out there for others to use if they wish, I would appreciate it if there was a least a really minimal READEME that briefly described what about this is different than the native integration.

I found this from a reddit post mentioning that it exposes some attributes directly "for a lovelace card" (so I'm guessing as sensors?), which does sound nice, but am wondering if there are anymore differences.

I know I can just try it out, but I'm a bit busy at the moment and was hoping at the least that you could share a few words about this mod before I tried it out.

Thanks.

**Comment by firstof9** [comment]
Added a README, let me know if that helps.

**Comment by oblivioncth** [comment]
Perfect, thanks.

That clarifies things.
